### DISCUSSION TITLE
[Request] unRAID Template?

### DISCUSSION THREAD

**Discussion by Kieranwest** [solidtime-io/solidtime#283] [Feature requests]
Hi, 
Love the look of solidtime. Unfortunately with the documentation currently available I'm finding it difficult to configure this to run on unRAID. Unsure if this is because solidtime cannot function outside of docker compose? 

Would love any advice :)
Thanks

**Comment by Onatcer** [comment]
i converted this into a discussion so people can upvote it if there is demand for it. 

as long as you can run docker you should be able to run the solidtime docker images, but i have never used unraid so I'm not sure how you would have to configure it, or what configuration options it gives you.

**Comment by markus-ruderman** [comment]
> Hi, Love the look of solidtime. Unfortunately with the documentation currently available I'm finding it difficult to configure this to run on unRAID. Unsure if this is because solidtime cannot function outside of docker compose?
> 
> Would love any advice :) Thanks

You can install **PortainerCE** https://unraid.net/community/apps?q=portainer in the meantime

![image](https://github.com/user-attachments/assets/d1650ed8-f360-4b5a-84b5-795832a62b1d)

and use it to create the solidtime stack.

I used the following `docker-compose.yml` configuration based on https://github.com/solidtime-io/self-hosting-examples/tree/main/1-docker-with-database 

```yaml
# https://www.solidtime.io/
# https://docs.solidtime.io/self-hosting/guides/docker
# https://docs.solidtime.io/self-hosting/configuration
# https://github.com/solidtime-io/solidtime
# https://hub.docker.com/r/solidtime/solidtime
#
# ISSUE:
# PASSPORT_PRIVATE_KEY and PASSPORT_PUBLIC_KEY environment doesn't work 
# => execute instead "php artisan passport:keys" to generate under 'storage/oauth-.*.key'
# https://stackoverflow.com/questions/39414956/laravel-passport-key-path-oauth-public-key-does-not-exist-or-is-not-readable

networks:
  backend:
    external: false

volumes:
  server-data:
    driver: local
  postgres-data:
    driver: local

services:
  server:
    restart: always
    image: solidtime/solidtime:${SOLIDTIME_IMAGE_TAG:-latest}
    container_name: solidtime_server
    user: "1000:1000"
    ports:
      - ${FORWARD_APP_PORT:-8000}:8000
    networks:
      - backend
    volumes:
      - server-data:/var/www/html/storage
    environment:
      CONTAINER_MODE: http
      AUTO_DB_MIGRATE: true
    env_file:
      - stack.env
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8000/health-check/up || exit 1" ]
    depends_on:
      - database
  
  scheduler:
    restart: always
    image: "solidtime/solidtime:${SOLIDTIME_IMAGE_TAG:-latest}"
    container_name: solidtime_scheduler
    user: "1000:1000"
    networks:
      - backend
    volumes:
      - server-data:/var/www/html/storage
    environment:
      CONTAINER_MODE: scheduler  
    env_file:
      - stack.env
    healthcheck:
      test: [ "CMD-SHELL", "supervisorctl status scheduler:scheduler_00" ]
    depends_on:
      - database
  
  queue:
    restart: always
    image: "solidtime/solidtime:${SOLIDTIME_IMAGE_TAG:-latest}"
    container_name: solidtime_queue
    user: "1000:1000"
    networks:
      - backend
    volumes:
      - server-data:/var/www/html/storage
    environment:
      CONTAINER_MODE: worker
      WORKER_COMMAND: "php /var/www/html/artisan queue:work"
    env_file:
      - stack.env
    healthcheck:
      test: [ "CMD-SHELL", "supervisorctl status worker:worker_00" ]
    depends_on:
      - database

  database:
    restart: always
    image: postgres:16
    container_name: solidtime_db
    environment:
      PGPASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s

```

In Portainer it looks like this:

![image](https://github.com/user-attachments/assets/92cbb044-6da9-4a9f-bff6-638ef73df878)

And at the *Environment variables* section you can switch to *Advanced mode*:

![image](https://github.com/user-attachments/assets/83d3d034-e2c8-46e6-9a21-a9ebfa95fe18)

and paste the environment settings there - check also https://docs.solidtime.io/self-hosting/configuration for the details:

```properties
APP_DOMAIN=https://your-domain.com
DB_DATABASE=solidtime
DB_USERNAME=solidtime
FORWARD_APP_PORT=18000
DB_PASSWORD=INSERT-YOUR-DB-PASSWORD-WHICH-YOU-WANT
SOLIDTIME_IMAGE_TAG=latest
APP_NAME="solidtime"
VITE_APP_NAME="solidtime"
APP_ENV="production"
APP_DEBUG="true"
APP_URL="https://your-domain.com"
APP_FORCE_HTTPS="true"
TRUSTED_PROXIES="0.0.0.0/0,2000:0:0:0:0:0:0:0/3"
SUPER_ADMINS=""
LOG_CHANNEL="stderr_daily"
LOG_LEVEL="debug"
DB_CONNECTION="pgsql"
DB_HOST="solidtime_db"
DB_PORT="5432"
DB_SSLMODE="require"
MAIL_MAILER="smtp"
MAIL_HOST="smtp.gmail.com"
MAIL_PORT="587"
MAIL_ENCRYPTION="tls"
MAIL_FROM_ADDRESS="your-mail@gmail.com"
MAIL_FROM_NAME="solidtime"
MAIL_USERNAME="your-mail@gmail.com"
MAIL_PASSWORD="GENERATE-AND-INSERT-GMAIL-APP-PASSWORD"
QUEUE_CONNECTION="database"
FILESYSTEM_DISK="local"
PUBLIC_FILESYSTEM_DISK="public"
APP_KEY="GENERATE-AND-INSERT-APP-KEY"
```

You need to change the above values to your target:
- `https://your-domain.com` - use your target domain - I tested hostname and port too and you have to set then `http://your-nas-name:18000`
- `APP_FORCE_HTTPS="true"` - change it to `false` if you use no domain and reverse proxy and therefore with hostname and port only
- `18000`- keep or change the port at which the solidtime application should be reachable, but adapt then the dependent parts
- `INSERT-YOUR-DB-PASSWORD-WHICH-YOU-WANT` - generate one with a password generator
- `your-mail@gmail.com` - if you use Google Mail then you can insert here your mail address, otherwise you have to adapt the other mail related settings too
- `GENERATE-AND-INSERT-GMAIL-APP-PASSWORD` - if you use Google Mail go to the App Password site in your Google Account and generate one for Solidtime - otherwise insert here the password of your target mail account
- `APP_KEY` - at https://generate-random.org/laravel-key-generator you can generate a key and paste it here - looks like this `base64:NHRrZXpiaHVyamlyY25ja3poenNzbHppMTJnMjluZXc=`

Then press the button `Deploy the stack` to create the stack.

Once it is up and running the stack looks like this in Portainer:

![image](https://github.com/user-attachments/assets/1724e4f0-50d7-4a7c-81bf-942e65aa5434)

Press the `Exec Console` button in Portainer at the `solidtime_scheduler` container:

![image](https://github.com/user-attachments/assets/c39ad202-cf08-46e4-893b-645efc6b179c)

![image](https://github.com/user-attachments/assets/e83c1b5f-ad71-448c-9444-b6439b0b15cf)

Then press `Connect` and inside the container shell execute `php artisan passport:keys` to generate the needed keys - they will be stored as 'storage/oauth-.*.key'.

![image](https://github.com/user-attachments/assets/95fb27da-3632-4091-846f-8594ba92ee12)

![image](https://github.com/user-attachments/assets/741bd197-ac34-432d-a9b8-b5b3d357f9ac)

Press the `Disconnect` button.

Go back to the solidtime stack:

![image](https://github.com/user-attachments/assets/5003d1f9-58a5-4307-b903-12243a98736b)

Select the `solidtime_queue`, `solidtime_scheduler` and `solidtime_server` container and press then the `Restart` button. 

When you have set `https://your-domain.com` to your domain then don't forget to configure your reverse proxy. If you have set to use `http://your-nas-name:18000` then the solidtime should be reachable now.

![image](https://github.com/user-attachments/assets/48afa388-ffa6-4a03-8644-51ddfe0e776d)

Press here then the `No account yet? Register here!` button.

![image](https://github.com/user-attachments/assets/aedf8031-e340-4c69-89a4-3698bdafa20e)

You have to use a reachable mail address because the application sends you then a link to validate the mail address.

Hope it helps 😄.
